spring.application.name=ReviewIt

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.vkicdzhdelcenjaibwoq
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

supabase.jwt.jwks-url=${SUPABASE_JWT_JWKS_URL}
supabase.jwt.issuer=${SUPABASE_JWT_ISSUER}

spring.web.error.include-stacktrace=never
